import { chromium } from 'playwright';
const OUT=process.env.OUT;
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2});
const p=await ctx.newPage();
const net=[];
p.on('request',r=>{if(/otp|verify|guest|signup/i.test(r.url()))net.push('REQ '+r.method()+' '+r.url());});
p.on('response',r=>{if(/otp|verify|guest|signup/i.test(r.url()))net.push('RES '+r.status()+' '+r.url());});
await p.addInitScript(()=>{localStorage.setItem('lecayenne.onboarding_seen','true');});
await p.goto('http://127.0.0.1:8087/',{waitUntil:'networkidle',timeout:30000});
await p.waitForTimeout(1500);
const inp=await p.$('.lc-device input[inputmode=tel]');
if(inp) await inp.fill('612345678');
await p.waitForTimeout(400);
await p.evaluate(()=>{const el=[...document.querySelectorAll('button')].find(b=>/RECEVOIR/.test(b.innerText));el&&el.click();});
await p.waitForTimeout(2500);
const lbl=await p.evaluate(()=>{const l=document.querySelector('[data-screen-label]');return l&&l.getAttribute('data-screen-label');});
const txt=await p.evaluate(()=>document.querySelector('.lc-device').innerText.slice(0,500));
console.log('LABEL',lbl);
console.log('TXT',JSON.stringify(txt));
console.log('NET',JSON.stringify(net,null,1));
await p.screenshot({path:OUT+'/06-otp.png'});
await b.close();
