import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * @FK-ID FK-WAVE-V-KDS-MULTIBUMP-001
 * @source P-OWNER Wave V (2026-05-21)
 *
 * Sentinel for the KDS rapid multi-order bump dispatch. Owner-reported bug:
 *  "Sur KDS et Suivi commandes : si je clique sur 'Prêt' deux fois (sur 2
 *   commandes différentes), ça me met la première en prête puis sur les
 *   autres ça donne 'trop de requêtes, réessayer après 30 secondes'. Mais
 *   après 30s ça refonctionne. Enlève cette sécurité — je veux valider 3
 *   commandes en même temps."
 *
 * Root cause: pre-Wave-V `KdsV2Grid.onCtaTap` used a single-slot pending
 * bump queue (shared `pendingTimeoutId`) + 3 s undo window. When the chef
 * tapped Prêt on a second order within 3 s, `clearTimeout(pendingTimeoutId)`
 * cancelled the FIRST order's deferred PATCH → only the LAST tap reached
 * the backend. Chef saw the cancelled tickets still EN COURS, re-clicked,
 * and intermittent 429 toasts (from unrelated upstream paths) rendered
 * the hardcoded "Trop de requêtes — patientez 30s" bootstrap.js copy.
 *
 * Heal: remove the 3 s undo window entirely. Each tap fires the
 * change-status emit synchronously with its own X-Idempotency-Key
 * (UUID v4 generated by buildIdempotencyHeaders) so concurrent PATCHes
 * on different orders are fully independent — backend OrderStateMachine
 * uses `lockForUpdate` per-order, no cross-order race.
 *
 * Structural invariants this sentinel locks:
 *   1. `pendingTimeoutId` does NOT appear in KdsV2Grid (was the per-component
 *      shared slot that caused the race).
 *   2. `activeToast` does NOT appear in KdsV2Grid (was the single-slot toast).
 *   3. KdsV2Grid does NOT import or register KdsUndoToast (the 3 s undo UI).
 *   4. `onCtaTap` calls `this.$emit('change-status', …)` SYNCHRONOUSLY
 *      (no wrapping `setTimeout`, no `clearTimeout`).
 *   5. `onUndo` method is removed (no undo path = no race surface).
 *   6. The step-ladder logic is preserved from Wave Q-2 (ACCEPT→PREPARING
 *      single step, PREPARING→PREPARED single step) so a single tap on a
 *      CONFIRMÉE ticket does NOT skip to PRÊT.
 *   7. The aria-live message is still emitted (a11y unchanged) — the
 *      `liveMessage` data field stays.
 *
 * Anti-regression: if any of these invariants drifts, chef-chained Prêt
 * taps would once again drop PATCHes on the floor.
 */
describe('KDS Wave V — Multi-order rapid bump dispatch (FK-WAVE-V-KDS-MULTIBUMP-001)', () => {
    const gridPath = resolve(
        process.cwd(),
        'resources/js/components/admin/kitchenDisplaySystem/KdsV2Grid.vue',
    );
    const gridSource = readFileSync(gridPath, 'utf8');

    // Helper: strip JS comments AND HTML <!-- --> comments so we can assert on
    // live code only. Heal comments are allowed to mention the removed
    // identifiers for documentation context without tripping the sentinel.
    const stripComments = (src) => src
        .replace(/\/\*[\s\S]*?\*\//g, '')
        .replace(/\/\/[^\n]*/g, '')
        .replace(/<!--[\s\S]*?-->/g, '');

    it('does NOT reference pendingTimeoutId in live code (the single-slot race vector)', () => {
        expect(stripComments(gridSource)).not.toMatch(/pendingTimeoutId/);
    });

    it('does NOT reference activeToast in live code (the single-slot toast state)', () => {
        expect(stripComments(gridSource)).not.toMatch(/activeToast/);
    });

    it('does NOT import KdsUndoToast (the 3 s undo UI)', () => {
        // Comment mentions are fine; actual `import … KdsUndoToast` line is not.
        expect(gridSource).not.toMatch(/^import\s+KdsUndoToast\s+from/m);
    });

    it('does NOT register KdsUndoToast in the components map', () => {
        // The `components: { ... }` literal should not list KdsUndoToast.
        const compsLine = gridSource.match(/components:\s*\{[^}]*\}/);
        expect(compsLine, 'expected a components: { … } definition').not.toBeNull();
        expect(compsLine[0]).not.toMatch(/KdsUndoToast/);
    });

    it('does NOT render <KdsUndoToast /> in the template', () => {
        expect(gridSource).not.toMatch(/<KdsUndoToast\b/);
    });

    it('onCtaTap emits change-status synchronously (no setTimeout wrap)', () => {
        // Slice the method body — from `onCtaTap(orderId, queueNo) {` to the
        // next top-level method `servedAgoLabel(` (or any closing balanced
        // brace at the methods level). We use a heuristic: capture up to the
        // next `,\n        // [` or `,\n        servedAgoLabel`.
        const methodMatch = gridSource.match(
            /onCtaTap\s*\([^)]*\)\s*\{([\s\S]*?)\n\s{0,12}\}\s*,\s*(?:\/\/|servedAgoLabel)/,
        );
        expect(methodMatch, 'expected onCtaTap method body to be parseable').not.toBeNull();
        const body = methodMatch[1];
        // The body must NOT contain a `setTimeout(` call — the racy wrapper.
        expect(body).not.toMatch(/setTimeout\s*\(/);
        expect(body).not.toMatch(/clearTimeout\s*\(/);
        // And it MUST emit change-status directly.
        expect(body).toMatch(/this\.\$emit\(\s*['"]change-status['"]/);
    });

    it('does NOT define onUndo method (undo flow removed)', () => {
        // Method definitions live inside `methods: { … }`. A `onUndo(` token
        // followed by `(` and `{` would imply a method definition.
        // (We tolerate `@undo` event bindings in templates — not present here.)
        expect(gridSource).not.toMatch(/^\s{4,}onUndo\s*\(/m);
    });

    it('preserves the Wave Q-2 step-ladder (ACCEPT→PREPARING | PREPARING→PREPARED)', () => {
        // Both branches of the ternary must be visible in onCtaTap.
        const ladder = gridSource.match(
            /currentStatus\s*===\s*ORDER_STATUS\.ACCEPT\s*[\r\n\s]*\?\s*ORDER_STATUS\.PREPARING\s*[\r\n\s]*:\s*ORDER_STATUS\.PREPARED/,
        );
        expect(ladder, 'expected the Wave Q-2 step-ladder ternary in onCtaTap').not.toBeNull();
    });

    it('preserves the aria-live message dispatch (a11y unchanged)', () => {
        expect(gridSource).toMatch(/this\.liveMessage\s*=\s*isFinalStep/);
        expect(gridSource).toMatch(/aria-live="polite"/);
    });

    it('keyboard shortcut path no longer gates on cash-pending (GOAL-2026-05-30 D1 owner reversal)', () => {
        // OWNER REVERSAL of Wave S-2: [A]–[H] may now bump a payment_pending_counter order
        // (kitchen prepares before encashment); onKey must NOT short-circuit on it.
        const m = gridSource.match(/onKey\s*\([^)]*\)\s*\{([\s\S]*?)\n        \},/);
        expect(m, 'onKey found').toBeTruthy();
        expect(m[1]).not.toMatch(/payment_pending_counter\s*===\s*true[\s\S]*?return/);
    });
});
