<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * [Wave F F-2 / Sprint 1C] Link order_payments → payment_terminals.
 *
 * Ajoute terminal_id NULLABLE à order_payments pour permettre :
 *   - traçabilité TPE physique par transaction (lecture audit / reporting Z)
 *   - calcul fees per terminal (fee_percent * amount + fee_fixed * count)
 *
 * NULLABLE pour ne pas casser les paiements legacy existants. ON DELETE
 * SET NULL : si un TPE est purgé (cas test), les paiements historiques
 * conservent leur trace mais perdent la jointure (cohérent avec le statut
 * 5=ARCHIVED qui privilégie le soft-delete).
 *
 * `mode` (et non `payment_method`) est le nom réel de la colonne du
 * `create_order_payments_table.php` migration.
 */
return new class extends Migration {
    public function up(): void
    {
        if (! Schema::hasTable('order_payments')) {
            return;
        }

        if (Schema::hasColumn('order_payments', 'terminal_id')) {
            return;
        }

        Schema::table('order_payments', function (Blueprint $table) {
            $table->unsignedBigInteger('terminal_id')->nullable()->after('mode');

            $table->index('terminal_id');

            $table->foreign('terminal_id')
                ->references('id')
                ->on('payment_terminals')
                ->nullOnDelete();
        });
    }

    public function down(): void
    {
        if (! Schema::hasTable('order_payments') || ! Schema::hasColumn('order_payments', 'terminal_id')) {
            return;
        }

        Schema::table('order_payments', function (Blueprint $table) {
            // Drop FK first (name auto-generated by Laravel : order_payments_terminal_id_foreign)
            try {
                $table->dropForeign(['terminal_id']);
            } catch (\Throwable $e) {
                // SQLite : no-op (no FK constraint enforcement in test env)
            }
            $table->dropIndex(['terminal_id']);
            $table->dropColumn('terminal_id');
        });
    }
};
