import { chromium } from 'playwright';
const OUT='/Users/1millnonstop/Downloads/projet/foodking-web/web/testttt/.claude/worktrees/cms-gestion-2026-06-10/reports/test-e2e/loyalty-global-2026-06-10';
const b = await chromium.launch();
const p = await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
await p.goto('http://127.0.0.1:8096/',{waitUntil:'networkidle'});
await p.waitForTimeout(2500);
await p.locator('button').filter({hasText:/Se connecter/}).first().click();
await p.waitForTimeout(1500);
await p.locator('input[type=email]').fill('ikyes@example.com');
await p.locator('input[type=password]').fill('motdepasse123');
await p.locator('.lc-modal button').filter({hasText:'Se connecter'}).last().click({force:true});
await p.waitForTimeout(3000);
console.log('TOP:', (await p.evaluate(()=>document.body.innerText.slice(0,260))).replace(/\n+/g,' | '));
await p.screenshot({path:OUT+'/L-B8-web-after-login.png'});
const fid = p.locator('header').locator('a,button').filter({hasText:'Fidélité'}).first();
console.log('fid count=', await fid.count());
if(await fid.count()) await fid.click({force:true}); else await p.locator('text=Fidélité').first().click({force:true});
await p.waitForTimeout(2500);
await p.screenshot({path:OUT+'/L-B8-web-loyalty-connected.png',fullPage:true});
console.log('LOYALTY:', (await p.evaluate(()=>document.body.innerText.slice(0,2500))).replace(/\n+/g,' | '));
await b.close();
