import { chromium } from 'playwright';
const OUT='/Users/1millnonstop/Downloads/projet/foodking-web/web/testttt/.claude/worktrees/cms-gestion-2026-06-10/reports/test-e2e/loyalty-global-2026-06-10';
const b = await chromium.launch();
const p = await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
await p.goto('http://127.0.0.1:8096/',{waitUntil:'networkidle'});
await p.waitForTimeout(2500);
await p.locator('button').filter({hasText:/Se connecter/}).first().click();
await p.waitForTimeout(1500);
await p.locator('input[type=email]').fill('ikyes@example.com');
await p.locator('input[type=password]').fill('motdepasse123');
await p.locator('.lc-modal button').filter({hasText:'Se connecter'}).last().click({force:true});
await p.waitForTimeout(2500);
const go = p.locator('button').filter({hasText:/Commencer à commander/});
if(await go.count()) await go.click({force:true});
await p.waitForTimeout(1500);
await p.locator('header').locator('a,button').filter({hasText:'Fidélité'}).first().click({force:true});
await p.waitForTimeout(2000);
const bal = async()=> (await p.evaluate(()=>document.body.innerText.match(/MON SOLDE\s*\n?\s*(\d+)/)?.[1]));
console.log('SOLDE BEFORE=', await bal());
await p.screenshot({path:OUT+'/L-B8-web-loyalty-before-use.png'});
const use = p.locator('button').filter({hasText:/UTILISER 3,47/i}).first();
await use.scrollIntoViewIfNeeded();
await use.click({force:true});
await p.waitForTimeout(2500);
console.log('SOLDE AFTER CLICK=', await bal());
const seg = await p.evaluate(()=>{const i=document.body.innerText.indexOf('UTILISE TES POINTS'); return document.body.innerText.slice(i,i+450);});
console.log('PANEL AFTER:', seg.replace(/\n+/g,' | '));
await p.screenshot({path:OUT+'/L-B8-web-loyalty-after-use.png',fullPage:true});
// check cart/panier for applied discount
await p.locator('header').locator('a,button').filter({hasText:'Panier'}).first().click({force:true});
await p.waitForTimeout(1500);
console.log('PANIER:', (await p.evaluate(()=>document.body.innerText.slice(-500))).replace(/\n+/g,' | '));
await p.screenshot({path:OUT+'/L-B8-web-panier-after-use.png'});
await b.close();
